<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="ru-RU">
<!--<![endif]-->

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{$meta_title}</title>
	<meta name="description" content="{$meta_description}">
	<meta name="keywords" content="{$meta_keywords}" />
	<meta name="author" content="Igor V. Kozinov" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- favicon generated by http://realfavicongenerator.net/ -->
	<link rel="apple-touch-icon" sizes="57x57" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/apple-touch-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/apple-touch-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/apple-touch-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/apple-touch-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/apple-touch-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/apple-touch-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/apple-touch-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/apple-touch-icon-180x180.png">
	<link rel="icon" type="image/png" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/favicon-32x32.png" sizes="32x32">
	<link rel="icon" type="image/png" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/favicon-194x194.png" sizes="194x194">
	<link rel="icon" type="image/png" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/favicon-96x96.png" sizes="96x96">
	<link rel="icon" type="image/png" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/android-chrome-192x192.png" sizes="192x192">
	<link rel="icon" type="image/png" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/favicon-16x16.png" sizes="16x16">
	<link rel="manifest" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/manifest.json">
	<link rel="mask-icon" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/safari-pinned-tab.svg" color="#5bbad5">
	<link rel="shortcut icon" href="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/favicon.ico">
	<meta name="msapplication-TileColor" content="#66e0e5">
	<meta name="msapplication-TileImage" content="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/mstile-144x144.png">
	<meta name="msapplication-config" content="{$smarty.const._URL}/templates/{$template_dir}/img/favicon/browserconfig.xml">
	<meta name="theme-color" content="#ffffff">
	<!-- end favicon links -->

	<link rel="stylesheet" href="{$smarty.const._URL}/templates/{$template_dir}/css/bootstrap.min.css" />
	<link rel="stylesheet" href="{$smarty.const._URL}/templates/{$template_dir}/css/normalize.min.css">
	<link rel="stylesheet" href="{$smarty.const._URL}/templates/{$template_dir}/css/animate.min.css">
	<link rel="stylesheet" href="{$smarty.const._URL}/templates/{$template_dir}/css/flickity.min.css">
	<link rel="stylesheet" href="{$smarty.const._URL}/templates/{$template_dir}/css/styles.css">
	<link rel="stylesheet" href="{$smarty.const._URL}/templates/{$template_dir}/css/block-news.css"">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

</head>

{if $tpl_name == 'index' || $tpl_name == 'video-watch'}



<script>{literal}

var pm_video_data = {
{/literal}	
	uniq_id: "{$video_data.uniq_id}",
	url: "{$video_data.video_href}",
	duration: {$video_data.yt_length|default:0},
	duration_str: "{$video_data.duration}",
	category: "{$video_data.category}".split(','),
	category_str: "{$video_data.category}",
	featured: {$video_data.featured|default:0},
	restricted: {$video_data.restricted|default:0},
	allow_comments: {$video_data.allow_comments|default:0},
	allow_embedding: {$video_data.allow_embedding|default:0},
	is_stream: {if $video_data.is_stream}true{else}false{/if},
	views: {$video_data.site_views|default:0},
	likes: {$video_data.likes|default:0},
	dislikes: {$video_data.dislikes|default:0},
	publish_date_str: "{$video_data.html5_datetime}",
	publish_date_timestamp: {$video_data.added_timestamp|default:0},
	embed_url: "{$video_data.embed_href}",
	thumb_url: "{$video_data.thumb_img_url}",
	preview_image_url: "{$video_data.preview_image}",
	title: '{$video_data.video_title|escape:'quotes'}',
	autoplay_next: {if $video_data.autoplay_next}true{else}false{/if},
	autoplay_next_url: "{$video_data.autoplay_next_url}"
{literal}
}
</script>
{/literal}
{/if}

{literal}
<script type="text/javascript">
 var pm_lang = {
	lights_off: "{/literal}{$lang.lights_off}{literal}",
	lights_on: "{/literal}{$lang.lights_on}{literal}",
	validate_name: "{/literal}{$lang.validate_name}{literal}",
	validate_username: "{/literal}{$lang.validate_username}{literal}",
	validate_pass: "{/literal}{$lang.validate_pass}{literal}",
	validate_captcha: "{/literal}{$lang.validate_captcha}{literal}",
	validate_email: "{/literal}{$lang.validate_email}{literal}",
	validate_agree: "{/literal}{$lang.validate_agree}{literal}",
	validate_name_long: "{/literal}{$lang.validate_name_long}{literal}",
	validate_username_long: "{/literal}{$lang.validate_username_long}{literal}",
	validate_pass_long: "{/literal}{$lang.validate_pass_long}{literal}",
	validate_confirm_pass_long: "{/literal}{$lang.validate_confirm_pass_long}{literal}",
	choose_category: "{/literal}{$lang.choose_category}{literal}",
	validate_select_file: "{/literal}{$lang.upload_errmsg10}{literal}",
	validate_video_title: "{/literal}{$lang.validate_video_title}{literal}",
	please_wait: "{/literal}{$lang.please_wait}{literal}",
	// upload video page
	swfupload_status_uploaded: "{/literal}{$lang.swfupload_status_uploaded}{literal}",
	swfupload_status_pending: "{/literal}{$lang.swfupload_status_pending}{literal}",
	swfupload_status_queued: "{/literal}{$lang.swfupload_status_queued}{literal}",
	swfupload_status_uploading: "{/literal}{$lang.swfupload_status_uploading}{literal}",
	swfupload_file: "{/literal}{$lang.swfupload_file}{literal}",
	swfupload_btn_select: "{/literal}{$lang.swfupload_btn_select}{literal}",
	swfupload_btn_cancel: "{/literal}{$lang.swfupload_btn_cancel}{literal}",
	swfupload_status_error: "{/literal}{$lang.swfupload_status_error}{literal}",
	swfupload_error_oversize: "{/literal}{$lang.swfupload_error_oversize}{literal}",
	swfupload_friendly_maxsize: "{/literal}{$upload_limit}{literal}",
	upload_errmsg2: "{/literal}{$lang.upload_errmsg2}{literal}",
	// playlist
	playlist_delete_confirm: "{/literal}{$lang.playlist_delete_confirm}{literal}",
	playlist_delete_item_confirm: "{/literal}{$lang.playlist_delete_item_confirm}{literal}",
	show_more: "{/literal}{$lang.show_more}{literal}",
	show_less: "{/literal}{$lang.show_less}{literal}",
	delete_video_confirmation: "{/literal}{$lang.delete_video_confirmation}{literal}",
	browse_all: "{/literal}{$lang.browse_all}{literal}",
	upload_error_unknown: "{/literal}{$lang.error_unknown|default:'Unknown error occured'}{literal}"
 }
</script>
{/literal}

<script type="text/javascript" src="{$smarty.const._URL}/js/swfobject.js"></script>

<body>
	<!--[if lt IE 8]>
	<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
	<div class="container-fluid">
		<div class="row">
			<div class="header-nav-wrapper">
				<div class="logo">
					<a href="{$smarty.const._URL}"><img src="{$smarty.const._URL}/templates/{$template_dir}/img/mfl-logo.png" alt="MFL TV - Открытая Студия"></a>
				</div>
				<div class="primary-nav-wrapper">
					<nav>
						<ul class="primary-nav">
							{if $live }<li><a href="{$smarty.const._URL}#intro">Эфир</a></li>{/if}
							<li><a href="{$smarty.const._URL}#guests">Последние участники</a></li>
							<li><a href="{$smarty.const._URL}#ng">Наш Город</a></li>
							<li><a href="{$smarty.const._URL}#events">События</a></li>
						</ul>
					</nav>
					<div class="secondary-nav-wrapper">
						<ul class="secondary-nav">
							<li class="subscribe"><a href="{$smarty.const._URL}#join-ng">Подписаться</a></li>
							<li class="search"><a href="#search" class="show-search"><i class="fa fa-search"></i></a></li>
						</ul>
					</div>
					<div class="search-wrapper">
						<ul class="search">
							<li>
								<input type="text" id="search-input" placeholder="Start typing then hit enter to search">
							</li>
							<li>
								<a href="#" class="hide-search"><i class="fa fa-close"></i></a>
							</li>
						</ul>
					</div>
				</div>
				<div class="navicon">
					<a class="nav-toggle" href="#"><span></span></a>
				</div>
			</div>
		</div>
	</div>

